[package]
name = "alternate-kv"
version = "0.1.0"
edition = "2024"

[dependencies]
alternate-codec = { workspace = true, optional = true }
alternate-migration = { workspace = true, optional = true }

anyhow.workspace = true
async-trait.workspace = true
deadpool-postgres = { version = "0.14.2", optional = true }
deadpool-redis = { version = "0.23.1", optional = true }
redis = { version = "1.6.0", optional = true }
rust-embed = { version = "8.12.0", optional = true }
serde = { workspace = true, optional = true }
thiserror.workspace = true
tokio = { version = "1.53.1", features = ["time"], optional = true }
tokio-postgres = { version = "0.7.18", optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
alternate-migration = { workspace = true, features = ["postgres"] }
testcontainers = "0.28.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "time"] }

[features]
default = ["tracing", "typed"]
postgres = ["dep:alternate-migration", "dep:deadpool-postgres", "dep:rust-embed", "dep:tokio", "dep:tokio-postgres"]
redis = ["dep:deadpool-redis", "dep:redis"]
tracing = ["dep:tracing"]
typed = ["dep:alternate-codec", "dep:serde"]

[lints]
workspace = true
