[workspace]
resolver = "3"
members = ["crates/email", "crates/http", "crates/kv", "crates/storage"]

[workspace.dependencies]
alternate-codec = { version = "0.1.0", registry = "self-hosted", git = "https://git.thealternate.dev/alternate/foundation", rev = "6ab3c110e76aac63cc775a6240603c533065671a" }

anyhow = "1.0.104"
async-trait = "0.1.92"
serde = "1.0.229"
thiserror = "2.0.20"
tracing = "0.1.44"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
must_use_candidate = "allow"
