[package]
name = "alternate-migration"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
blake3 = "1.8.7"
jiff.workspace = true
thiserror.workspace = true
tokio = { version = "1.53.1", optional = true }
tokio-postgres = { version = "0.7.18", features = ["with-jiff-0_2"], optional = true }

[features]
default = []
postgres = ["dep:tokio", "dep:tokio-postgres"]

[lints]
workspace = true
